language: python
python:
- 2.7
env:
  global:
  - DOCKER_CONTENT_TRUST=0
  - secure: iSziuUQ9vINJVgnU0TTuAhOLXTDI0Sqy2E/MESa3pQMm31xXjhKBnFLJBfUftY/Isuj+VRBtyVRXCHloVs+pC4LMdz/7nLY7QevTSdDqJPyYU38OxQSj1kD8hNPVikv6YiKJ1DQhxiI7UgOaWrX4Yt1uadkJERsdlHGdwHDjgwxHR7CDAlLE9BmrTOQEduIzbdcJcUSiuzpt3abYi6M2iVW+IcBS/cFKTe6j85Lb+TeD1t7xBRC8932dQ9DTiXz/oiYSfT+Z0Vq+NkCjudFjTA0A9Z86EPllXH+5d34vxRt5U/68Ham7f1qduGmF1kr97eSmG0tvKaLr9+kdWpKGmcPfcHDM/xhXgpmXtq2YNXp7dAsx4JwgSZLIYtNTEg/OniVyJ3NzNJoRwmT2H7BGhvbgMJWSV/MRiYAjvBpD/j9ld0gpG+oSvIDCld54hcHTLsgO/H3bm2RLvnhKHmkaJeurT0L20Y9xZlvz/Av47rKT9fbti1QVsBXmh4Fw0oEk+RLoid75/oCUKKuHZ1uR1/bf6LqjQCnBPuEkXAjdCI4HkSk4mICkoAzKrUePEnfc8YyiTTwFSin7ECtkNzKhDXansdPl9ofKg5FHce6sumbgFoQ/XKc5emXIPn5W+U7ReaIh4I8NSxvNb5XiHT/Y1RWJOft+3tXILZZe0EbpWHI=
  - secure: q/KTu7rYgTpwdqmoypYwqAYupjh5yEX+OGroGZCUBz7z86VJtFIK+QvCmoKD3kIKG7MwhnmjxNcGYvkBFJ3GZNjcucJ/AfTY24MrR1xJMu9DrzmFBeyqN+8FxPnA+q0aP1zt2456bGo4nonYotqn39HSAX4bDCYsaZcLpeAVeFiBwdI8R+J7FBj3L1XKday/FaRw5O1esdQLZWYDddSyo63qAqxnsBr3Fm/Oum5aF2DxNfMDYS4L/Baai4ZfsSJw/8nHCo8TXitkWdJa3MJRx+spNaZKEAURFguKAD6wFEU6gVo+af9ReigcPsmSt25IyYAq1gMDqA/d6M2IRxR9bWRl+rvEOB04qP8mWV7mXDduILYVnGA7oegFuyNB+XiSTmU1W2FHPx3tMxdbR3AYlumr/jpmqXupg8cr2WWAEYxl+SirUJw8I5QMZcKd/5vvexsahQKjZQrSeIVjOedQwX76wKKzc0+0M5WzSe0K5XqkJR3zNEt541w0jz/HCg0YgGKcJtMB/k+Y7PY3vgRSn0bPpNYjiD+s2X4suGqzxRQwBlpXErAH17MvgSXzodu2CXcf841dQFFVtPf8HnGK9WiX3SuRGLG+AVdDkVDAmSE0SWcXymOg0bxmfAxv5gcl4t0DgzM22e2CwY6wk4VEAQ+bbAGZ0yGsfOJmyxbe1u4=
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v1_6_7
- docker-compose build
- docker-compose up -d
- docker-compose ps
- docker exec --user=oscar -it oscar /sandbox.sh
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd $TRAVIS_BUILD_DIR/v1_6_7
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker-compose images
- docker push trydirect/django-oscar:1.6.7
