language: python
python:
- 2.7
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
  - secure: J9et+Pg/vS/cWk1XhSF+SzJMiuHdu63PbR6PLkEIiyL1znWThOQMvlxny9vp/cIGPtK3Q1rxwWI+0AWyFNOVpTF9aQkulLGuXCt3tFV0ILmG9fM2CQ006Rs0Q8eOKxT01hTcl6jJlmLNL1OkMP32TQSu9oUj+KpqN2jQdmYJTQg49JzCX+cqDQEPvSW9bmm24QKycjgao7e+Al2i5r8yZeNem0O2ZVECYxKxyzFC6R0MS0bkihxhTxR98cmLvOmXGtbYfJf7vBh/9PiMUHy2Sxwz+8a4zO8pdrTdtGjL9rsFmRSIhYS9NtFPaNuBRPTK41JtinIb7cVNneZmdtus6ZoSy8OvtkWmVfbs6v7RmVf2nWO69cugUGICFCvV2wfDVSmdEiZd67n9o3qRV7d3q9S0DG5hfCGMI1lC1KYb8gHoDs2wKr0vdwMxWZwzUliBbTd2jBa/MnukfO67UgCN+wh5JXXtqLcvzB/gpssomaKHXDX9W2pwp538PTM9Rb51WVPBlKn5KVjbcysKBCm3ZkOdbCYgVU6HDlnsWYjUH8nvKHGsmfACCxDBGJM7MbGjZzqqmhkcgA4rSypgAwqtC4dmYFnxr4ZNd3qI2jWIZ6uQalmv4wEW5KJNPlzQHcKipF9fKhfGfL/QNb+kNY2tocNLkTiK4vkeKI+mtpAP84I=
  - secure: VXED2m6dh9zMSDe+oD4egV0MppOCYG429dGqx4p0o9gLDOMFB7UKV7IxVNtohzLaFFPiDOajKEuYP0p+jo8JxE5hduFJsiY4/E5a9e5xOwR/c3OldOR066SRzmq2EwwfTGI1J59P3hqlqC8qZD86EPluEk5emU5eemtxHqidPcj4lqK0RrZ0yMd+4FSyDzURN8YIj91VUUuWXWSq0smDvV1ATNbCY9g7kz9wfV3yvgbMDQMlFD9gWWKRlRTXBL0jIVfT1K1ntZuCbBa1LqHUFs6xn3IfNXCvb16cjhVoOBdzv8KAy5ddKbesP3sLLABwHvry7Igi+w+oVBMmUVg9mInTvP9LEJ673s48YeiJiQkd4aAMAPVBJ12EBrrVmKhB8HYLTdso+HE9q9NW3N8t0FXaGZMFx/F34gtvLn7zclyYV4JebpHl1d/D/FITuafF3oQjbqxtDmeC4ie86yZFwHk1J9Srl+aI28WvfgJyn6SHv9F+H57Gfx7u4leMIX8S3JVRANnrg0r1R1HKObIqoacDxSI+qPC/U7jm1RzV+r9XBLJn+hVZ0jYQwG+D7eRJQQwl/YOvpQKZIyoYRQP8la1YMtazKRWKVZZDYY5Mx8uAMHxVQaTuLU7OwBduPvNjqFQTt0NHHQVBn4FPmZBH+mBSnDm7LnLwNf9mjvu7pmM=
  global:
  - secure: hYYYiE6QhS3+csVbk6MlGb4xK+eUnV7zFrc+4UkrGOYT5ayGNIB/xOBcrDNBMulwJh6gnCqEsyunm6Iz2UbvDQH5M+7isA+RBW3w4b7HI3k791TZ8ywfy5EwuSERClyT/58DQ6RRc+TglVsCQKHlxEnHan3aqovuqARocqf3m5+OzToIuJRqa82q1qV1IyKaqyaq3rNAykMtuQrUVfMMF4hzsa9MkXoiBSxhpAdxQNk3mcE2+SZn3sSOkakbpoQffSkRQVPzlQRuRBYyLnbTTUH7Ud3jL2SQqgBwbE2GEIuoAfSMgGhY9Esu9feXFZFZsxdWgkYfbGM/AX4C5DfmoYSYxI8sZZfQxr2wVOebp42zukRH9Vd/4MmFkTbutAHWr+ML2TLlJVHXEXA3SGuK0fxwK92coie7nF9gx58Vb09PtG/rqRhfTq8LuqOcDUpe38oZEAFUd3SqOcy4NqFqzkDxB5kGXneEGYx8C4FAmpC/fk2p/jMe5cLvlJ6daGv/JQIAiU3qs171PVCqbTP/Yz2RaK409vENwwcFbIfJhcv1yXxjJ4yXLHJIemyp4FjX0yK0l8PS4jsDwhpKwOblpxZrYBCRdUTwaNJIOJoWgpUIjcLRWLKjrhwF85nPafyCeFDskvdxOfL38eEDbk2wq+pS6vbBFi25mJaNHEh2VXM=
  - secure: GQLvtw8xtTAcmqEtb3P4V15uvXWHhdUpgnSEYiR61FPNolvgqXIFmLqPu1nPKaKOSK5P8iTKhHtVkXaZOX9+NmGL/bdNYaWvCFY4D5hyqOULDeaxdHKudAOh0CMg/Q2Pq2F8OH0C8yTDpAyuF/NyGlZuqL5QrDX7mZnHCZH2zf3aKbfBsine2ezXkMSDQNB1xTzTyKxx0xwuq2FeFWHISR2pKjemSTnW29z0pJi9ugcFxCxPGzdi/WJ8xiLCxqspAp3bNjvPQQBjlPf90maDR91jv59rR4+QXUXoYEOJ8m0jPt6qM9+55mdCcDsCexnAKKyel9oUa03QOyzXTwm9Y7RlhzWe2vReBTg+AfFJV/cBvUVxz+6WGZv7wepowyx4okysu7l3+Lm1wWR720jqSuj4h7tYXdLp9u1aaxlpJ9OdooutMN64iyBnFXAE3GvKF3h5SvqnOsUU0XhRIrrKcwQgKvJZFdCkfvsU2nbyZqBlBCpEvCXrEChpP9KHVn+pqG+T5ZKd+KengfBf+pKdD8dl9pZtLRfM1ufqFOo9sAAlde+lrs0OBSB1jVhyhurdQLgUoam7eeN0i4o7p2T4DHGUQ2QApGtRr2IGAw2K+TBODwWnUf2jJuBJhhWvPIj+tVzkW3t8ZNuQE+TwmeoedtHJ6M6DAiecef9c/jKdEUE=
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v1_6_7
- docker-compose build
- docker-compose up -d
- docker-compose ps
- docker exec --user=oscar -it oscar /sandbox.sh
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd $TRAVIS_BUILD_DIR/v1_6_7
- echo $DOCKER_USERNAME
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker-compose images
- docker push trydirect/django-oscar:1.6.7
