language: python
python:
- 2.7
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
  global:
  - secure: gjIMpng7Kkb8p1dwL37UteYmeaErv/k8SrL9k/XyJbwPwTGhB6pmeEqN2oO4sEuhMK67m+aljQqKrjCCocRWCmk8NVm88sjbR8NmwX3ez9WyAs3fkoGUMGuYeTgueM5rT9Rb3nR8BAlIkJ7lvaxdHLvRcLBYiiwCaRd3zMhx238X5PNxpRsMSnbnvD4B91jim4QEypv15TzuHJFU6ZCvVOs0wyYB1reV0+jdjGjS0fyUzqq4rZ4eB6zp3A3oVBsVKUbzYPGUkE9T6d0LJ58ahiKWfsvAEjTnjOxA/NTUw4Dll5bCWiQlP/MojJDOnsvn5/lG2oIwHEHa3tJ5YcdaUle2kNE5FAe9d4EH2rFxrXFCPp9+hSBafcEsROTDMsddK3SkjjFVo26Hepwzgej51dslGwfBwye5R2G1HSenUd0EcMCjPzIFT75z4kiDkuT1MnJkcKIL0f9CX+Z63MMXdcjGz2nDg+O8QMjvwlFEDGnVWYfW7dXBncdmDaAmHimzz7xH9O6HZ99wH4/4CyvKP/696w49/Oghvn9eDIa+lFbGKFZiOAls5gQTbQmY+b4cgeskpEM5o6P2BKkGxdJZv1rE9Z2dH9ztQPQEltwIBN+AhyezZiYXSvDxJ+86LQar7g2vcBbymqbygk7yswG0MsmvvIQj51ouV2E6pWhVWpo=
  - secure: TQ9t6oYFeU82tRj/7cNc2g/QTpQAT/rStBxy90RdeGsf6vUr/OOb9UBemcX4ztI+HN59Z0YqoolZrHPSfJU61VwcacW4wK0bpi/7LLhFG7EIkW7T3i64z9ukj/f3XlPNE0421+C3s/EN6ND5oy7qbSIoL3bzaU9X7NW1wFk6dOocWTwCQwuiOk5GZLs1CCiDQko6/IdNHvKPdB8rftEknPT+rimnxP/VgctrB6OX8TztwQMsFXNVnm2sBWjR7OvA9RTrQlTsl/zgCss4sbC5q+wG7NTP5CDQ5pnbGVMjzkJzp8wCLYBurvKtHf79PfXBdInOA2xRUfrNlgsWxItiu/qIRndtQigxTMMFxrD1KOGVikkBvu8XnxJDNZ+ntSbEcxpDT51mdA2P2c3rIUPdso/BiKIawSmqBJnNn8FXhxBvO0cMJ7sZBf98OxEYY2C3bLQ4v0o031eNjMliSI3p0vI8hvFbU0VnYcGlrIvtY3sRyAl6foNOYnxICw6JMk7EtAodpuAo+toKO4rG1coQVprXLuo6Nv1aSfV7zHPG1Y7/VfFxGBYOjRyqzkySDnyU+SxJSHVblUflk+Q5Z2Jz8Cryi672sQQ5/gT53LFiqCQkmZvbKmhSqNpraPao3s50PvBnYowtv8v8qAFtBm9mcVocHR9g21v30NTVDj8t55k=
  - secure: KSgEiBhU6Z3fnZdJg5E+2JWgfokhd516qpM/PG4D35c1rPbHbRA5tiLOJYUZsMj3K90q/6k/BD+ZbWmFVMiiqXG2FKqMxwZQXdoO/TyKCuzgEKDFAe9bkP93S3VgLlsoR55jAT8vWXrfdKwdtKKGYy5pl3tA+y/TsYnLOG97OOpm0D6fyJANwPPIvmka9G8CtOHW7g/uRBDkwPADMLUvpyjv8Mfy19K2AHiXhJJoR+M1snBUgEN/zal/VbCPyKHY5/sZGfTLt6vc3tYCOhWaQFVXzHJboNbjkYygQ0vpE3rth69ARJA6miiyNM3+RQgnBdRiGgziRl2m9vVyHDczSf22wBCVziD8VBdpZ229mv2Cukgzenym1A0kvk+gOtC7LVLMMzFWJ5X6iGbo6156jwA4xYMKfY6tNHF27M6xnnI9CJSvzju9SjjvX9cl3dtOkbHU2TL0j2/BrFN23RIDeqHR8ArYPMAYivWElc3nSp7+CT+ECaRRzttcGmyoKEVMw7WnnnjJaN/X+tsmwjWvw9htumAGmYpVu8F3s3yeFYoRzkm04brgL92btMsgQpRo8kmwagIHIGOFeAQSWwx9F1Vtxj825DX8XCT+4iyyS50zjQmsQ4ykcJpvS5bOzgeuEemgKgEr8R0RWoKyB5S+9KNc22uS8oUspftSiFHMjaE=
  - secure: JXoNa92gSF2SVPJh72HM9AJpEbLg/yG1x2qI0LDsN1LSZZbjQP1Cbkg5SRX0dv2HpbyjFenlwsxzx2hTnyNAF9CKm4MRg1KY7EqxxcrLcWhcJzJvocCeVxlHxCJuR9iB59glFXDzHZF7UEtaSQ4NfkguufcQSKz1S8TnmUU/cKYQR1Ss/fLt4LcI8jwK8t3IKqIZO74O2xYIdVvkYlvhredZXrbkxMZ1jEUIBoNLghgO1c6zSZG2thTqry21pKb0dB9OXy9VfwNVIh9nDDCp1axu9whtY/pymlvvIeYcmPZiFNjrhNTWMMumUqiu0vLJ4A9IwNBpoaRM4s2pTOMnE37bonfBNyZLb1G7JyM0PSSvHk+TS2TfU7q/YG3gjbbOqpJdReZRkxhROicuLvbnq6HWXK14fuYBfHVbN+CyLFDGpUnjZc4rJ4/dQZNDsddVr5j3f1veiGKdr2fi0J+N4UvMu4eCMpQM6BnecxYEApTSa/LxE0aHp7wpo6QcapIF0pBHU+xXFzLIMTxnVER8PoYvx61P6x/4I6SiVS6akHJS7DgMrMfFJvCqaEymdI+75J4sBk5IloiThphGgVfGbG+qKe/+wLOi8b4jyog8+HQtHx0coaw2PEIcHSFeU6I5hJC3y6BsWuvGerZBxd3thUTldyIkhvIlqReS+brLSpg=
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v1_6_7
- docker-compose build
- docker-compose up -d
- docker-compose ps
- docker exec --user=oscar -it oscar /sandbox.sh
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd $TRAVIS_BUILD_DIR/v1_6_7
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker-compose images
- docker push trydirect/django-oscar
