language: python
python:
- 2.7
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
  global:
  - secure: YC7ShyUep+5GDVgOcsCMJ5Y+o4RORfR9DT+fbCNbTVuLODyaQDWSdWYFRky/ek/2X45eY+SQarCdKCP0giWiX/5HS7PHewPwKyYLTwsGTUp1Aq8CgMOY4IFscUdHW/wgVeI3obiSXFYBcbZRGkjuNU5BEuSlcIVzYPYsdGLHP09kpdDMRFz8rRDsASxh3scIBDQYi1nXtQpPTc18me1MqL4OsrfG3u6r/1yOe8qAw3Q3zQbpR6f+uc5TzWhker8G8C9Q/tHceM98NpudCA9xyI7Vxu/mifDmSck615fJBAUqsnJq+xFBE436qbMsq2+VMEppdYCx4DQVQyirwc5FQP+dcOSo/ctW3vp4/pjR3M56zjkwUWE3y45fKnUZt7LHgyibYHJar3XQakY7wB+KPOHwHrEs77Q2Yrde81Th2Xb6dMTphKopIZyrBYxaBDe04QOJsQwNJp+zv2ANXgF0PBJl0CMveJr4xTJ7z1uD4dYuxlRw9PBIQs9ZaenbLUoHyw8ho94YmZIeGG5sYmIqUE0/4Tv8rvL81osK6BxN5YV1C+klUyOo0W2pCUOIIH8fWHXOrEFud3VJJv7R1zeI4xdZKOhEHHCfSX3VKrwbVN9/jMLyvxbSnwdmg0AF2gLpChs78as10H6WyH1aFfaT+PW0DbvYUNyuA2nuHWAJ/W8=
  - secure: QiblZEG0zd/D3t55sUTyM4WLrO5tFu+Itloxo570GTrepU7oDDum/DfMKaetr3uC/34buSCQJS5/TnNcLKWnqPaYtCW7qzKQRor0SGF4mN8ooi0uuIDeRaydJRbtVtNQKQhVy4WPouDvmkEM/EYfs+7wyLDX1P6yadMytVsDAutAaEW8jBw4BXdZDP99MgZodvJ1j8Bsh33jNK0EkiC+HVbCERZIzhX3X6uETSOGMRTpXX3q3LO0M2D8uEzd5U6p/5VNO658960J5ESYsUzCFEqI/Q82Io9Tbb4b/l6eiVCAsu+YlgpA33KZq8FWEqvTvn2DxP+spnjH7TS571zbNdkaALTxHjCZ61Zl5jcNL1DWeTjDgZvsECnpMxKhqG2YpE8W861ghIeUJkN3EZz4oD85yhahm4UZZBuFkCaTKmvupS9F6WaJiZbSfYO24iIVr5lDRy74ZYu7J+K2C2bwdUWGrjq3F9MPq0AzMFVKDeN3Ds2z9riX9UHlJzIM0ffISLWHMFCe5hebjAFri0nrj2VRngXf6t+se7oZJP4a9P1v+qphGQnFnYQIpqtgKvsmfOEjaRa1dmPWsGIhRhm3MNjcdntq+dANMUX4nRKc2LIodtmOsv6oyUQAKAce7BgrNG+gTSupri20pTrJbfdzFhrd+jNMRXnN23y6zCCOwJg=
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v1_6_7
- docker-compose build
- docker-compose up -d
- docker-compose ps
- docker exec --user=oscar -it oscar /sandbox.sh
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd $TRAVIS_BUILD_DIR/v1_6_7
- echo $DOCKER_USERNAME
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker-compose images
- docker push trydirect/django-oscar:1.6.7
