language: python
python:
- 2.7
env:
  global:
  - DOCKER_CONTENT_TRUST=0
  - secure: aFS2/e8gadycu6N9PNCiaJODMFnTbGhQaGOa1MJa2+itVsdykB/K4hjV0hiK7Iv8HQPt3dKJ55Eg0KBzW5rZ6NqOJxh1DKZ853DTEfX/uwH0BUvITc2Sf6yGmhOUYAH1tu9MsbTV3kkX4vdBQF6qIf+R6wCcSdVfPWKaSCurA4T86mQOarcbDGa7CGf/SYYKf2pCcqKD4Pb/36aUFuwxhwxhSkzpXiqNgM9CIBoGNkSGqdZilSSKc5VzHMrgmsi1T9EIaBmETPJXlkNODeazY+W6nkP+SLIsyoQGBs5Maed1h3t26JUJLMtfqLr+Jj6uN4EE5Lep/pBa2CqwMRKFIERfq35a6Nxqh06IAflS1z3cR1YxScaHTT89Nd+769kaC9LNSVX9cXoLI3agZ+2AIG81ZWMGU6wmfnmwlf8y4svaPMp0nOLkqKDju7be4r+dRb4tJaDqVq9YKvslcNxOhfER6DMgacYf9p/0UkXEw5+4vYrqc8+oxEdibT10MeC1i8bwOPVFR2Ckz1+PjIK9lyhM6nAf3A2Fsptn9jgh6q4qsFpbpEtveQ6DFL/DJyiWrb+oB+4SxOeRRSQ7junI4CJMXfYwUCJr6iPOHSZWYuIlGqtis+FrWuTdc0IgFECmih6KUdPD/rpxTxAeJgto73BLvqGUM53boQCkfjsivDM=
  - secure: WNrlFXEmdw/Vu2bfPzvLKdj2CdOv5VJPXi2gt5zL/+XZ6M3Z34M35CQR5anjv6RMFV5+FMODdTReq8DOoRBIEkWJb7QSX6jr5+H+Xd/805ctR3DM33en1dj3B2Ggc3aACcFbsEIH3tSU9+o3MNgy/USfTWM52tZL3z0492vQBbx4nbM+cH5p+GH4kb9xUsl6Pi1/Qw3bnvuVfJkgucwcWjnNFGKvB3NhfxVgkEcKi57ow70k7RGXD/QPn2Wo976Pa+F+1y5WjveWvcXF0EF/ZNuZSYibjbZK7aMLBjoxix9muZ8KK1pIt3fBuwLhqQTAiXfxyJsNZCHEb+pjFvy2/0dAwJxkUuplcFAp626vBznBVk0UQkhiRnq555t0XQBqXnFHFOuAUs9EzE5Q7o6GLEcz3To/AceFmKuIPFJeJAF2LE6H30mVVyCaeKgjHjHLVtyLWGoSK9E1kgDuNwrpUYVN/nH5+ZPjk4pgxnOLJb0ml34KbcWZgkaBwPge2ph9raAmxEWUO82oId0L0DDLFKBYgWZNGPCrmkE7ZLJ72EYQNUkIkzgCw3bD9J2Ub+18chCqgytta+1YYv7ycx1L/5dftcSlWDu34Fcei5T7PUbIpkTFfyGVH/DuIGbTMgSbZciNeiPScEXiDspCqU7kGVfH9J4v+EJuOvfymaK65q0=
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v1_6_7
- docker-compose build
- docker-compose up -d
- docker-compose ps
- docker exec --user=oscar -it oscar /sandbox.sh
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd $TRAVIS_BUILD_DIR/v1_6_7
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker-compose images
- docker push trydirect/django-oscar:1.6.7
